---
title: "Startle Data"
format: html
editor: visual
---

## Loading in the Libraries for Everything

```{r}
library(tidyverse)
library(ggplot2)
library(bbmle) #For ICtab
library(car)
library(ggpubr)
library(ggdist)
library(emmeans)
library(lme4)

```

## School Summary Stats

```{r}
school_data <- read.csv("Data/Fish_School_Values_3D.csv")
school_data <- na.omit(school_data)

school_data <- school_data %>% mutate(Flow = ifelse(Flow == "0", "Still Water", "Flowing Water (2 BL/s)")) %>%
                           mutate(Ablation = ifelse(Ablation == "N", "No Ablation", "Ablated")) %>%
                           mutate(Darkness = ifelse(Darkness == "N", "Light", "Dark")) %>%
                           filter(School_Speed <= 5) %>%
                           mutate(Flow = factor(Flow), Ablation = factor(Ablation), Darkness = factor(Darkness)) %>%
                           mutate(Flow = fct_relevel(Flow, c("Still Water","Flowing Water (2 BL/s)"))) %>%
                           mutate(Ablation = fct_relevel(Ablation, c("No Ablation","Ablated"))) %>%
                           mutate(Darkness = fct_relevel(Darkness, c("Light","Dark"))) %>%
                           mutate(Flow_Ablation_Darkness = factor(paste(Flow,Ablation,Darkness,sep=", "))) %>%
                            
                           # ### Used to remove every third point to reduce autocorrelation
                           mutate(Date = paste(Year,Month,Day,sep="_"),
                                  Date_Trial = paste(Year,Month,Day,Trial,sep="_"),) %>%
                           # group_by(Date_Trial) %>%
                           # filter(row_number() %% 3 != 1) %>%
                           # ungroup() %>%
                           # ###
                          
                           group_by(Flow_Ablation_Darkness) %>%
                           mutate(NND_Mean_Val = mean(NND), NND_SD_Val = sd(NND),
                                  Polar_Mean_Val = mean(School_Polar), Polar_SD_Val = sd(School_Polar),
                                  Speed_Mean_Val = mean(School_Speed), Speed_SD_Val = sd(School_Speed),
                                  Area_Mean_Val = mean(Area), Area_SD_Val = sd(Area),
                                  Groups_Mean_Val = mean(Groups), Groups_SD_Val = sd(Groups),
                                  Mean_Groups_Mean_Val = mean(Mean_Groups), Mean_Groups_SD_Val = sd(Mean_Groups),
                                  Height_Mean_Val = mean(School_Height), Height_SD_Val = sd(School_Height)) %>%
                           ungroup()
```

## Startle Conditions

```{r}

startle_school_data <- read.csv("Data/Startle_First_Half_Fish_School_Values.csv")
startle_school_data <- na.omit(startle_school_data)

startle_school_data <- startle_school_data %>% mutate(Flow = ifelse(Flow == "0", "Still Water", "Flowing Water (2 BL/s)")) %>%
                           mutate(Ablation = ifelse(Ablation == "N", "No Ablation", "Ablated")) %>%
                           mutate(Darkness = ifelse(Darkness == "N", "Light", "Dark")) %>%
                           filter(School_Speed < 7) %>%
                           mutate(Flow = factor(Flow), Ablation = factor(Ablation), Darkness = factor(Darkness)) %>%
                           mutate(Flow = fct_relevel(Flow, c("Still Water","Flowing Water (2 BL/s)"))) %>%
                           mutate(Ablation = fct_relevel(Ablation, c("No Ablation","Ablated"))) %>%
                           mutate(Darkness = fct_relevel(Darkness, c("Light","Dark"))) %>%
                           mutate(Flow_Ablation_Darkness = factor(paste(Flow,Ablation,Darkness,sep=", "))) %>%
                           group_by(Flow_Ablation_Darkness) %>%
                           mutate(NND_Mean_Val = mean(NND), NND_SD_Val = sd(NND),
                                  Polar_Mean_Val = mean(School_Polar), Polar_SD_Val = sd(School_Polar),
                                  Speed_Mean_Val = mean(School_Speed), Speed_SD_Val = sd(School_Speed),
                                  Area_Mean_Val = mean(Area), Area_SD_Val = sd(Area)) %>%
                           ungroup() %>% 
                           mutate(Exp_Label = paste0("Darkness Pre-Startle ",Trial))

startle_school_data_light <- school_data %>% filter(Darkness == "Light" & Ablation == "No Ablation" & Flow == "Still Water") %>%
                                             mutate(Exp_Label = "Light") %>%
                                             select(-c(Z_SD, Groups, Groups_Mean_Val,Groups_SD_Val,
                                                       School_Height, Height_Mean_Val, Height_SD_Val))

startle_school_data <- rbind(startle_school_data_light,startle_school_data) %>% 
                       mutate(Exp_Label = factor(Exp_Label)) %>%
                       mutate(Exp_Label = fct_relevel(Exp_Label,c("Light",
                                                                  "Darkness Pre-Startle 1",
                                                                  "Darkness Pre-Startle 5",
                                                                  "Darkness Pre-Startle 30")))

```

```{r}

my_comparisons <- list(c("Light", "Darkness Pre-Startle 1"), c("Light", "Darkness Pre-Startle 5"), c("Light", "Darkness Pre-Startle 30"))

nnd_startle <- ggplot(startle_school_data,
       aes(x = Exp_Label, y = NND,
           color = interaction(Ablation,Darkness,sep=", "),
           fill = interaction(Ablation,Darkness,sep=", ")))+
  stat_dots(side = "both", binwidth = unit(dot_binwidth, "npc")) +
  geom_point(aes(y = NND_Mean_Val), size = 3, color = "Black") +
  geom_errorbar(aes(ymin=NND_Mean_Val-NND_SD_Val, ymax=NND_Mean_Val+NND_SD_Val), width=.2, color = "Black")+
  guides(fill = guide_legend(title = "Condition")) +
  scale_fill_manual(values=c(light_no_ab_color, dark_no_ab_color, dark_no_ab_color)) +
  scale_color_manual(values=c(light_no_ab_color, dark_no_ab_color, dark_no_ab_color)) +
  #ggtitle("Effect of Available Senses on Nearest Neighbor Distance (NND) in Still Water") +
  xlab("") +
  ylab("NND (BL)") +
  theme_light()+ 
  theme(legend.position = "none") +
  #ylim(0,3)+
  stat_compare_means(comparisons = my_comparisons, label = "p.signif", hide.ns = TRUE) +
  theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.y = element_text(size = 15))

polar_startle <- ggplot(startle_school_data,
       aes(x = Exp_Label, y = School_Polar,
           color = interaction(Ablation,Darkness,sep=", "),
           fill = interaction(Ablation,Darkness,sep=", ")))+
  stat_dots(side = "both", binwidth = unit(dot_binwidth, "npc")) +
  geom_point(aes(y = Polar_Mean_Val), size = 5, color = "Black") +
  geom_errorbar(aes(ymin=Polar_Mean_Val-Polar_SD_Val, ymax=Polar_Mean_Val+Polar_SD_Val), width=.2, color = "Black")+
  guides(fill = guide_legend(title = "Condition")) +
  scale_fill_manual(values=c(light_no_ab_color, dark_no_ab_color, dark_no_ab_color)) +
  scale_color_manual(values=c(light_no_ab_color, dark_no_ab_color, dark_no_ab_color)) +
  #ggtitle("Effect of Available Senses on Polarization in Still Water") +
  xlab("") +
  ylab("Polarization") +
  theme_light()+ 
  theme(legend.position = "none") +
  #ylim(0,1.15)+
  stat_compare_means(comparisons = my_comparisons, label = "p.signif", hide.ns = TRUE) +
  theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.y = element_text(size = 15))

speed_startle <- ggplot(startle_school_data,
       aes(x = Exp_Label, y = School_Speed,
           color = interaction(Ablation,Darkness,sep=", "),
           fill = interaction(Ablation,Darkness,sep=", ")))+
  stat_dots(side = "both", binwidth = unit(dot_binwidth, "npc")) +
  geom_point(aes(y = Speed_Mean_Val), size = 5, color = "Black") +
  geom_errorbar(aes(ymin=Speed_Mean_Val-Speed_SD_Val, ymax=Speed_Mean_Val+Speed_SD_Val), width=.2, color = "Black")+
  guides(fill = guide_legend(title = "Condition")) +
  scale_fill_manual(values=c(light_no_ab_color, dark_no_ab_color, dark_no_ab_color)) +
  scale_color_manual(values=c(light_no_ab_color, dark_no_ab_color, dark_no_ab_color)) +
  #ggtitle("Effect of Available Senses on Speed (BL/s) in Still Water") +
  xlab("") +
  ylab("Speed (BL/s)") +
  theme_light()+ 
  theme(legend.position = "none") +
  #ylim(0,8.5)+
  stat_compare_means(comparisons = my_comparisons, label = "p.signif", hide.ns = TRUE) +
  theme(axis.text.x = element_text(size = 15),
        axis.text.y = element_text(size = 15),
        axis.title.y = element_text(size = 15))

nnd_startle
polar_startle
speed_startle


ggsave("Paper Figures/startle_nnd.png", nnd_startle, width = 12, height = 7)

```
